UserManagmentSystem/Models/GroupsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UserManagmentSystem.Models
{
    public class GroupsViewModel
    {
        public int PK_Id { get; set; }
        public string Name { get; set; }
        public List<UsersViewModel> Users { get; set; }
        public List<ActionsViewModel> Actions { get; set; }

        public GroupsViewModel()
        {
            Users = new List<UsersViewModel>();
            Actions = new List<ActionsViewModel>();

        }
    }
}

UserManagmentSystem/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using UserManagmentSystem.Models;

namespace UserManagmentSystem.Controllers
{
    [Authorize]

    public class GroupsController : Controller
    {
        private ModelEntities db = new ModelEntities();

        // GET: Groups
        public ActionResult Index()
        {
            return View(db.tblGroups.ToList());
        }

        // GET: Groups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblGroups tblGroups = db.tblGroups.Find(id);
            if (tblGroups == null)
            {
                return HttpNotFound();
            }

            GroupsViewModel groupsViewModel = new GroupsViewModel();
            ImplementedMethods implementedMethods = new ImplementedMethods();
            groupsViewModel.Name = tblGroups.Name;
            groupsViewModel.PK_Id = tblGroups.PK_Id;
            groupsViewModel.Actions = tblGroups.tblGroupActions.Select(s => new ActionsViewModel
            {
                PK_Id = s.PK_Id,
                Name = s.ActionName
            }).ToList();
            
            ViewBag.AvailableActions = implementedMethods.ActiveMethods.Where(t => !db.tblGroupActions.Any(k => k.FK_Group == id && k.ActionName == t)).Select(s => new SelectListItem { Value = s, Text = s }).ToList();


            return View(groupsViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RevokeAction(int GroupId, string ActionName)
        {
            tblGroupActions tblGroupActions = db.tblGroupActions.FirstOrDefault(s => s.FK_Group == GroupId && s.ActionName == ActionName);
            if (tblGroupActions != null)
            {
                db.tblGroupActions.Remove(tblGroupActions);
                db.SaveChanges();
            }


            return RedirectToAction("Details", new { id = GroupId });
        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddAction(int GroupId, string ActionName)
        {
            tblGroupActions tblGroupActions = new tblGroupActions() { ActionName = ActionName, FK_Group = GroupId };
            if (tblGroupActions != null)
            {
                db.tblGroupActions.Add(tblGroupActions);
                db.SaveChanges();
            }


            return RedirectToAction("Details", new { id = GroupId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RevokeUser(int GroupId, string UserId)
        {
            tblUserGroup tblUserGroups = db.tblUserGroup.FirstOrDefault(s => s.FK_Group == GroupId && s.FK_User == UserId);
            if (tblUserGroups != null)
            {
                db.tblUserGroup.Remove(tblUserGroups);
                db.SaveChanges();
            }


            return RedirectToAction("Details", new { id = GroupId });
        }
        // GET: Groups/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Groups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PK_Id,Name")] tblGroups tblGroups)
        {
            if (ModelState.IsValid)
            {
                db.tblGroups.Add(tblGroups);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblGroups);
        }

        // GET: Groups/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblGroups tblGroups = db.tblGroups.Find(id);
            if (tblGroups == null)
            {
                return HttpNotFound();
            }
            return View(tblGroups);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PK_Id,Name")] tblGroups tblGroups)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblGroups).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblGroups);
        }

        // GET: Groups/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblGroups tblGroups = db.tblGroups.Find(id);
            if (tblGroups == null)
            {
                return HttpNotFound();
            }
            return View(tblGroups);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblGroups tblGroups = db.tblGroups.Find(id);
            db.tblGroups.Remove(tblGroups);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UserManagmentSystem/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UserManagmentSystem.Models;

namespace UserManagmentSystem.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private ModelEntities db = new ModelEntities();

        // GET: Users
        public ActionResult Index()
        {
            return View(db.AspNetUsers.ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUsers aspNetUsers = db.AspNetUsers.Find(id);
            if (aspNetUsers == null)
            {
                return HttpNotFound();
            }

            UsersViewModel usersViewModel = new UsersViewModel();
            usersViewModel.Id = aspNetUsers.Id;
            usersViewModel.LockoutEnabled = aspNetUsers.LockoutEnabled;
            usersViewModel.LockoutEndDateUtc = aspNetUsers.LockoutEndDateUtc;
            usersViewModel.Name = aspNetUsers.UserName;
            usersViewModel.PhoneNumber = aspNetUsers.PhoneNumber;
            usersViewModel.PhoneNumberConfirmed = aspNetUsers.PhoneNumberConfirmed;
            usersViewModel.TwoFactorEnabled = aspNetUsers.TwoFactorEnabled;
            usersViewModel.UserName = aspNetUsers.UserName;
            usersViewModel.Groups = db.tblUserGroup
                .Where(s => s.FK_User == aspNetUsers.Id)
                .Select(s => new GroupsViewModel()
                {
                    PK_Id = s.FK_Group,
                    Name = s.tblGroups.Name
                }).ToList();

            ViewBag.AvailableGroups = db.tblGroups.Where(t => !db.tblUserGroup.Any(k => k.FK_User == id && k.FK_Group == t.PK_Id))
                .Select(s => new SelectListItem { Value = s.PK_Id.ToString(), Text = s.Name }).ToList();

            return View(usersViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RevokeGroup(int GroupId, string UserId)
        {
            tblUserGroup tblUserGroups = db.tblUserGroup.FirstOrDefault(s => s.FK_Group == GroupId && s.FK_User == UserId);
            if (tblUserGroups != null)
            {
                db.tblUserGroup.Remove(tblUserGroups);
                db.SaveChanges();
            }


            return RedirectToAction("Details", new { id = UserId });
        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddGroup(int GroupId, string UserId)
        {
            tblUserGroup tblUserGroups = new tblUserGroup()
            {
                FK_Group = GroupId,
                FK_User = UserId
            };
            if (tblUserGroups != null)
            {
                db.tblUserGroup.Add(tblUserGroups);
                db.SaveChanges();
            }


            return RedirectToAction("Details", new { id = UserId });
        }


        // GET: Users/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUsers aspNetUsers = db.AspNetUsers.Find(id);
            if (aspNetUsers == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUsers);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            AspNetUsers aspNetUsers = db.AspNetUsers.Find(id);
            db.AspNetUsers.Remove(aspNetUsers);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UserManagmentSystem/Views/Groups/Create.cshtml
@model UserManagmentSystem.Models.tblGroups

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <button type="submit" class="btn btn-info">Submit</button>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UserManagmentSystem/Views/Groups/Delete.cshtml
@model UserManagmentSystem.Models.tblGroups

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblGroups</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UserManagmentSystem/Views/Groups/Details.cshtml
@model UserManagmentSystem.Models.GroupsViewModel
@using UserManagmentSystem.Models
@using UserManagmentSystem.Controllers
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>tblGroups</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Users</h3>

        <div class="card-tools">
            <span class="badge badge-success">@Html.DisplayFor(model => model.Users.Count) Members</span>

        </div>
    </div>
    <!-- /.card-header -->
    @if (Model.Users.Count > 0)
    {
        <div class="card-body">
            <div class="row">
                @foreach (UsersViewModel user in Model.Users)
                {
                    <div class="col-md-4">
                        <div class="card card-widget widget-user-2">
                            <!-- Add the bg color to the header using any of the bg-* classes -->

                            <div class="widget-user-header bg-warning">
                                <div class="card-tools">
                                    @using (Html.BeginForm("RevokeUser", "Groups", new { UserId = user.Id, GroupId = Model.PK_Id }, FormMethod.Post, null))
                                    {
                                        @Html.AntiForgeryToken()

                                        <button type="submit" value="Delete" class="btn btn-tool float-right">
                                            <i class="fas fa-times"></i>

                                        </button>
                                    }
                                </div>
                                <div class="widget-user-image">
                                    <img class="img-circle elevation-2" src="#" alt="User Avatar" height="65" width="65">
                                </div>
                                <!-- /.widget-user-image -->
                                <h3 class="widget-user-username">@user.Name</h3>
                                <h5 class="widget-user-desc">@user.Postition</h5>
                            </div>
                            <div class="card-footer p-0">
                                <ul class="nav flex-column">
                                    <li class="nav-item">
                                        <a class="nav-link">
                                            Orders <span class="float-right badge bg-primary">@user.OrdersConut</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>

                    </div>

                }
            </div>
            <!-- /.users-list -->
        </div>
    }

    <!-- /.card-body -->
    <div class="card-footer text-center">
        <a href="javascript:void(0)" onclick="location.href='@Url.Action("Index","Users")'">View All Users</a>
    </div>
    <!-- /.card-footer -->
</div>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Actions</h3>

        <div class="card-tools">
            <span class="badge badge-success">@Html.DisplayFor(model => model.Actions.Count) Actions</span>

        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body">



        @if (Model.Actions.Count > 0)
        {
            <div class="row">
                @foreach (ActionsViewModel action in Model.Actions)
                {

                    <div class="col-md-6">
                        <div class="card card-outline card-success">
                            <div class="card-header">
                                <h3 class="card-title"> @action.Name</h3>

                                <div class="card-tools">


                                    @using (Html.BeginForm("RevokeAction", "Groups", new { GroupId = Model.PK_Id, ActionName = @action.Name }, FormMethod.Post, null))
                                    {
                                        @Html.AntiForgeryToken()

                                        <button type="submit" value="Delete" class="btn btn-tool">
                                            <i class="fas fa-times"></i>

                                        </button>
                                    }

                                </div>
                                <!-- /.card-tools -->
                            </div>

                        </div>
                        <!-- /.card -->
                    </div>


                }

            </div>
        }


    </div>
    <!-- /.card-body -->
    <div class="card-footer ">
        @using (Html.BeginForm("AddAction", "Groups",
           new { GroupId = Model.PK_Id, ActionName = "ActionName" }, FormMethod.Post, null))
        {
            @Html.AntiForgeryToken()
            <div class="row">
                <div class="col-md-6">
                    @Html.DropDownList("ActionName", new SelectList(ViewBag.AvailableActions, "Value", "Text"), htmlAttributes: new { @class = "form-control ui  search selection dropdown " })

                </div>
                <div class="col-md-6">
                    <input type="submit" value="Add New Action" class="btn btn-default" />
                </div>
            </div>


        }
    </div>
</div>



<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PK_Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

UserManagmentSystem/Views/Groups/Edit.cshtml
@model UserManagmentSystem.Models.tblGroups

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblGroups</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PK_Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UserManagmentSystem/Views/Groups/Index.cshtml
@model IEnumerable<UserManagmentSystem.Models.tblGroups>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PK_Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.PK_Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PK_Id })
        </td>
    </tr>
}

</table>